// Generated from clinic_vocab.py — edit that file, then re-run the export.
// Every list was read from BPC's own Jane account. Modalities are a closed list.
window.VOCAB = {
 "NOT_ASSESSED": "-",
 "BLANK": "___",
 "PAIN_TYPE": [
  "Dull",
  "Sharp",
  "Radiating",
  "Throbbing",
  "Stiffness",
  "Numbness",
  "Shooting",
  "Tingling",
  "Burning",
  "Aching",
  "Clicking",
  "Locking",
  "Giving way"
 ],
 "AGGRAVATING": [
  "Worse on walking",
  "Worse on stairs",
  "Worse on sitting",
  "Worse on standing",
  "Worse in the morning",
  "Worse at night",
  "Worse on lifting",
  "Worse on overhead activity",
  "Worse on squatting",
  "Worse after exercise",
  "Worse on driving"
 ],
 "EASING": [
  "Better with rest",
  "Better with movement",
  "Better with heat",
  "Better with stretching",
  "Better after treatment",
  "Better with medication"
 ],
 "OBSERVATION": [
  "Normal posture",
  "Forward head",
  "Round shoulder",
  "Scapular protraction",
  "Scapular winging",
  "Shoulder level Rt.>Lt.",
  "Shoulder level Lt.>Rt.",
  "Clavicle asymmetry",
  "Thoracic hyperkyphosis",
  "Thoracic flattened",
  "Flatback",
  "Lumbar hyperlordosis",
  "Anterior pelvic tilt",
  "Posterior pelvic tilt",
  "Pelvic asymmetry",
  "Symmetrical PSIS",
  "Hip elevation Rt.",
  "Hip elevation Lt.",
  "Lumbar shift to Rt.",
  "Lumbar shift to Lt.",
  "Scoliosis",
  "No scoliosis",
  "Genu valgum (knock knee)",
  "Genu varum (bow leg)",
  "Genu recurvatum",
  "Patella alta",
  "Patellar lateral shift",
  "Flat feet",
  "No flat feet",
  "Pes cavus",
  "Swelling",
  "Muscle atrophy",
  "Bruising",
  "Scar",
  "Redness",
  "Increased skin temperature",
  "Antalgic gait",
  "Non-weight bearing (NWB)",
  "Partial weight bearing",
  "On crutches",
  "In moon boot",
  "Poor posture",
  "Forward head posture",
  "Chin out",
  "Uneven shoulder",
  "Mild flat feet",
  "Thoracic hypokyphosis (flat back)",
  "Head shift to left",
  "Head shift to right",
  "Knee valgus",
  "Knee varus"
 ],
 "OBSERVATION_BY_REGION": {
  "Ankle & foot": [
   "Foot posture Rt.: neutral / supination / pronation",
   "Foot posture Lt.: neutral / supination / pronation"
  ]
 },
 "PALPATION_FINDINGS": [
  "Tenderness",
  "Tightness",
  "Trigger point",
  "Muscle spasm",
  "Swelling",
  "Warmth",
  "Joint stiffness",
  "Crepitus",
  "Hypomobility",
  "Hypermobility"
 ],
 "PALPATION_NORMALS": [
  "No palpable warmth",
  "Normal skin temperature",
  "No swelling",
  "No atrophy",
  "No tenderness",
  "No trigger point"
 ],
 "MUSCLES": {
  "Neck & shoulder": [
   "upper trapezius",
   "middle trapezius",
   "lower trapezius",
   "levator scapulae",
   "rhomboid",
   "sub-occipital",
   "cervical paraspinal",
   "sternocleidomastoid",
   "scalene",
   "supraspinatus",
   "infraspinatus",
   "subscapularis",
   "teres minor",
   "teres major",
   "pectoralis major",
   "pectoralis minor",
   "serratus anterior",
   "latissimus dorsi",
   "anterior deltoid",
   "middle deltoid",
   "posterior deltoid",
   "biceps",
   "brachialis",
   "triceps",
   "long head of biceps"
  ],
  "Trunk & back": [
   "erector spinae",
   "quadratus lumborum (QL)",
   "lumbar paraspinal",
   "thoracic paraspinal",
   "multifidus",
   "transversus abdominis",
   "rectus abdominis",
   "oblique",
   "diaphragm",
   "iliocostalis"
  ],
  "Hip & thigh": [
   "gluteus maximus",
   "gluteus medius",
   "gluteus minimus",
   "tensor fasciae latae (TFL)",
   "piriformis",
   "iliopsoas",
   "hip adductor",
   "adductor magnus",
   "quadriceps",
   "vastus medialis",
   "vastus lateralis",
   "rectus femoris",
   "hamstring",
   "biceps femoris",
   "semitendinosus",
   "ITB",
   "sartorius"
  ],
  "Knee & lower leg": [
   "popliteus",
   "gastrocnemius",
   "soleus",
   "tibialis anterior",
   "tibialis posterior",
   "peroneus longus",
   "peroneus brevis",
   "patellar tendon",
   "achilles tendon",
   "plantar fascia",
   "flexor hallucis longus",
   "extensor digitorum"
  ],
  "Forearm & hand": [
   "wrist extensor group",
   "wrist flexor group",
   "common extensor origin",
   "common flexor origin",
   "thenar",
   "hypothenar",
   "pronator teres",
   "supinator",
   "first dorsal interosseous"
  ]
 },
 "SIDES": [
  "Rt.",
  "Lt.",
  "Both",
  "Rt.>Lt.",
  "Lt.>Rt."
 ],
 "ROM_GENERAL": [
  "Flexion",
  "Extension",
  "Abduction",
  "Adduction",
  "ER",
  "IR"
 ],
 "ROM_BY_REGION": {
  "General / other": [
   "Flexion",
   "Extension",
   "Abduction",
   "Adduction",
   "ER",
   "IR"
  ],
  "Neck / cervical": [
   "Neck flexion",
   "Neck extension",
   "Neck lateral flexion Rt.",
   "Neck lateral flexion Lt.",
   "Neck rotation Rt.",
   "Neck rotation Lt."
  ],
  "Shoulder": [
   "Shoulder flexion",
   "Shoulder extension",
   "Shoulder abduction",
   "Shoulder adduction",
   "Shoulder IR",
   "Shoulder ER",
   "Hand behind back"
  ],
  "Elbow, wrist & hand": [
   "Elbow flexion",
   "Elbow extension",
   "Supination",
   "Pronation",
   "Wrist flexion",
   "Wrist extension",
   "Radial deviation",
   "Ulnar deviation"
  ],
  "Thoracic spine": [
   "Thoracic flexion",
   "Thoracic extension",
   "Thoracic rotation Rt.",
   "Thoracic rotation Lt."
  ],
  "Trunk / lumbar": [
   "Trunk flexion",
   "Trunk extension",
   "Trunk lateral flexion Rt.",
   "Trunk lateral flexion Lt.",
   "Trunk rotation Rt.",
   "Trunk rotation Lt."
  ],
  "Hip": [
   "Hip flexion",
   "Hip extension",
   "Hip abduction",
   "Hip adduction",
   "Hip IR",
   "Hip ER"
  ],
  "Knee": [
   "Knee flexion",
   "Knee extension"
  ],
  "Ankle & foot": [
   "Ankle dorsiflexion",
   "Ankle plantarflexion",
   "Subtalar inversion",
   "Subtalar eversion",
   "Hallux dorsiflexion"
  ]
 },
 "REGIONS": [
  "General / other",
  "Neck / cervical",
  "Shoulder",
  "Elbow, wrist & hand",
  "Thoracic spine",
  "Trunk / lumbar",
  "Hip",
  "Knee",
  "Ankle & foot"
 ],
 "ROM_QUALIFIERS": [
  "full ROM without pain",
  "full ROM with pain at end range",
  "full ROM with tightness",
  "limited 3/4 range by pain",
  "limited 1/2 range by pain",
  "limited by tightness",
  "limited by muscle guarding",
  "full AROM all directions",
  "full PROM all directions"
 ],
 "ACCESSORY_BY_REGION": {
  "Ankle & foot": [
   "Talocrural",
   "Subtalar",
   "Talonavicular joint",
   "Calcaneocuboid",
   "1st ray mobility",
   "Distal tibiofibular"
  ],
  "Knee": [
   "Patellofemoral joint",
   "Tibiofemoral joint",
   "Proximal tibiofibular joint"
  ],
  "Shoulder": [
   "Glenohumeral joint",
   "AC joint",
   "SC joint",
   "Scapulothoracic"
  ]
 },
 "STRENGTH": [
  "UE grossly 5/5",
  "LE grossly 5/5",
  "UE limited",
  "LE limited",
  "Weakness",
  "Good muscle power",
  "Grade 3/5",
  "Grade 4/5",
  "Grade 5/5",
  "Normal",
  "WNL",
  "Intact",
  "Isometric test",
  "MMT",
  "N/A due to severity of pain",
  "Middle and lower trapezius weakness",
  "Rhomboid muscle weakness",
  "Weakness of core muscle",
  "Gluteus medius weakness",
  "Neck flexor weakness"
 ],
 "PAIVMS": [
  "Central PA at",
  "Right unilateral PA",
  "Left unilateral PA"
 ],
 "FUNCTIONAL": [
  "Sit to stand double legs",
  "Sit to stand single leg",
  "Squat",
  "Single leg squat",
  "Deep squat",
  "Overhead squat",
  "Step down test",
  "Step up test",
  "Hop test",
  "Double balance",
  "Single leg balance",
  "Gait analysis",
  "Stair climbing",
  "Heel raise",
  "Bulgarian split squat",
  "Knee to wall",
  "Hand behind back",
  "Hand behind neck",
  "Overhead deep squat",
  "Single leg stand",
  "Single leg RDL",
  "Pogos",
  "Balance test",
  "Arm raise",
  "Multisegmental rotation",
  "Multisegmental flexion",
  "Multisegmental extension"
 ],
 "FUNCTIONAL_BY_REGION": {
  "Ankle & foot": [
   "Double leg squats",
   "Single leg squats",
   "Single leg balance",
   "Hop test",
   "Heel raise"
  ]
 },
 "OVERHEAD_SQUAT": [
  "Normal",
  "Excessive trunk flexion",
  "Excessive hip IR",
  "Excessive hip ER",
  "Excessive knee adduction",
  "Excessive knee abduction",
  "Excessive foot pronation",
  "Excessive foot ER",
  "Decreased weightbearing",
  "Unable to complete due to pain or weakness"
 ],
 "MYOTOMES": [
  "C5",
  "C6",
  "C7",
  "C8",
  "T1",
  "L2",
  "L3",
  "L4",
  "L5",
  "S1"
 ],
 "DERMATOMES": [
  "C5",
  "C6",
  "C7",
  "C8",
  "T1",
  "L2",
  "L3",
  "L4",
  "L5",
  "S1"
 ],
 "NEURO_PHRASES": [
  "Dermatomes: WNLs sensory screening bilateral UE and LEs",
  "Myotomes: Key muscle groups grossly equal bilaterally",
  "Reflexes: Bicep (C5): ___, Brachioradialis (C6): ___, Tricep (C7): ___",
  "No neurological deficit"
 ],
 "SPECIAL_TESTS": [
  "FABER",
  "FADIR",
  "Noble test",
  "Ober test",
  "Thomas test",
  "Trendelenburg",
  "SLR",
  "Slump test",
  "Prone instability test",
  "Spurling test",
  "Neer test",
  "Hawkins-Kennedy",
  "Empty can test",
  "Full can test",
  "Speed's test",
  "Yergason test",
  "Apprehension test",
  "Sulcus sign",
  "Lachman test",
  "Anterior drawer (knee)",
  "Posterior drawer",
  "Valgus stress test",
  "Varus stress test",
  "McMurray test",
  "Thessaly test",
  "Patellar grind",
  "Patellar apprehension",
  "Anterior drawer (ankle)",
  "Talar tilt",
  "Squeeze test",
  "Calcaneal tilt test",
  "Thompson test",
  "Windlass test",
  "Phalen test",
  "Tinel sign",
  "Finkelstein test",
  "Cozen test",
  "Mill's test",
  "Sacroiliac compression",
  "Gaenslen test",
  "Adam's forward bend test",
  "Craniocervical flexion test",
  "Compression test",
  "Distraction test",
  "PKB (prone knee bend)",
  "SIJ distraction",
  "SIJ compression",
  "Kemp test",
  "Ely test",
  "Hawkins test"
 ],
 "POSITIONS": [
  "Supine lying",
  "Prone lying",
  "Side lying to Rt.",
  "Side lying to Lt.",
  "Sitting",
  "Standing",
  "Long sitting",
  "Half lying",
  "Four point kneeling"
 ],
 "TREATMENT_MODES": [
  "cont. mode",
  "pulse mode",
  "analgesic mode",
  "anti-inflammation mode"
 ],
 "TREATMENT_MODALITIES": {
  "Ultrasound (US)": "US  Position: ___  Area: ___  Parameter: ___ MHz, ___ w/cm2, ___ mins",
  "US combined with stim": "US combine  Position: ___  Area: ___  Parameter: ___ MHz, ___ w/cm2, Stim ___ V, ___ mins per point for ___ points",
  "US + IFC": "US + IFC at ___ in ___: cont. mode, ___ MHz, int. ___ w/cm2, ___ V, ___ min",
  "IFC (interferential current)": "IFC  Area: ___  Parameter: ___ Hz, ___ V, ___ mins",
  "TENS": "TENS  Area: ___  Parameter: ___ Hz, ___ V, ___ mins",
  "Electrical stimulation": "Electrical stimulation  Area: ___  Parameter: ___ Hz, ___ mins",
  "High power LASER (HPLT)": "HPLT at ___  Mode: anti-inflammation / analgesic, ___ J/cm2",
  "Shockwave therapy": "Shockwave  Area: ___  Parameter: ___ bar, ___ Hz, ___ shots",
  "Peripheral magnetic stimulation (PMS)": "PMS  Area: ___  Parameter: ___ Hz, ___ mins",
  "Neck traction": "Neck traction  ___ kg, ___ mins",
  "Pelvic traction": "Pelvic traction  ___ kg, ___ mins",
  "Hot pack": "Hot pack (large / small) on ___, ___ mins",
  "Cold pack": "Cold pack on ___, ___ mins",
  "Massage": "Massage: ___",
  "Stretching": "Stretching: ___",
  "Passive stretch": "Passive stretch: ___, ___ sec x ___ reps",
  "Joint mobilization": "Joint mobilization grade ___  Area: ___",
  "Spinal mobilization": "Spinal mobilization grade ___  Area: ___",
  "Cupping": "Cupping  Area: ___, ___ mins",
  "Taping": "Taping: ___  Area: ___",
  "Home advice": "Home advice: ___",
  "Gym": "Gym: ___",
  "Home program": "Home program: ___",
  "Stretching exercise": "Stretching exercise: ___"
 },
 "POST_TREATMENT": [
  "After treatment no complication",
  "E: Tension release, no complications after treatment",
  "Re-assessment: No complication after treatment",
  "Post treatment: feels relief",
  "Post treatment: pain decreased",
  "Post treatment: ROM improved"
 ],
 "SUBJECTIVE_PHRASES": [
  "Pain less but need to continue treatment",
  "Patient feels better after the last treatment",
  "Same symptoms as last visit",
  "มารักษาต่อเนื่อง",
  "ปวดตึงคอบ่าลดลง",
  "อาการดีขึ้นจากครั้งก่อน"
 ],
 "SESSION_LENGTHS": [
  "Session 60 minutes",
  "Session 90 minutes",
  "CPG 60 mins",
  "CPG 90 mins",
  "CPG 45 mins"
 ],
 "EXERCISES": {
  "Neck & upper back": [
   "Chin tuck",
   "Chin tuck with lift",
   "Cervical retraction",
   "Deep neck flexor activation",
   "Upper trapezius stretch",
   "Levator scapulae stretch",
   "Sub-occipital release",
   "Scapular retraction",
   "Scapular squeeze",
   "Wall angel",
   "Prone Y raise",
   "Prone T raise",
   "Prone W raise",
   "Serratus wall slide",
   "Thoracic extension over foam roller",
   "Thoracic rotation open book",
   "Cat camel",
   "Band row",
   "Face pull",
   "Doorway pec stretch"
  ],
  "Shoulder": [
   "Pendulum",
   "Wall slide",
   "Shoulder flexion AAROM with stick",
   "Shoulder abduction AAROM with stick",
   "External rotation with band",
   "Internal rotation with band",
   "Isometric ER",
   "Isometric IR",
   "Isometric abduction",
   "Sleeper stretch",
   "Cross-body stretch",
   "Side-lying ER",
   "Full can raise",
   "Scaption raise",
   "Push-up plus",
   "Bear crawl hold",
   "Overhead press",
   "Landmine press",
   "Rhythmic stabilisation"
  ],
  "Elbow, wrist & hand": [
   "Wrist extensor eccentric",
   "Wrist flexor eccentric",
   "Tyler twist",
   "Grip strengthening with ball",
   "Wrist extension with band",
   "Supination / pronation with weight",
   "Nerve glide — radial",
   "Nerve glide — median",
   "Nerve glide — ulnar",
   "Tendon glide",
   "Thumb opposition",
   "Putty exercises"
  ],
  "Trunk & core": [
   "Transversus abdominis activation",
   "Dead bug",
   "Bird dog",
   "Plank",
   "Side plank",
   "Plank with shoulder tap",
   "Pallof press",
   "Glute bridge",
   "Single leg glute bridge",
   "Hip thrust",
   "Curl up",
   "Bicycle crunch",
   "Hollow hold",
   "Diaphragmatic breathing",
   "Pelvic tilt",
   "McGill big three",
   "Suitcase carry",
   "Farmer carry"
  ],
  "Hip & pelvis": [
   "Clamshell",
   "Clamshell with band",
   "Side-lying hip abduction",
   "Standing hip abduction with band",
   "Monster walk",
   "Lateral band walk",
   "Hip flexor stretch",
   "Piriformis stretch",
   "ITB stretch",
   "Adductor stretch",
   "90/90 hip rotation",
   "Hip hinge",
   "Romanian deadlift (RDL)",
   "Single leg RDL",
   "Bulgarian split squat",
   "Split squat hold",
   "Step up",
   "Lateral step down",
   "Copenhagen plank"
  ],
  "Knee": [
   "Quad set",
   "Straight leg raise (SLR)",
   "Heel slide",
   "Terminal knee extension (TKE)",
   "Mini squat",
   "Wall sit",
   "Squat",
   "Goblet squat",
   "Leg press",
   "Leg extension",
   "Hamstring curl",
   "Nordic hamstring curl",
   "Step up",
   "Step down",
   "Single leg squat",
   "Spanish squat",
   "VMO activation",
   "Isometric knee extension hold",
   "Cycling",
   "Treadmill walking",
   "Return-to-run progression"
  ],
  "Ankle & foot": [
   "Ankle pump",
   "Alphabet ankle ROM",
   "Dorsiflexion stretch",
   "Calf stretch — gastrocnemius",
   "Calf stretch — soleus",
   "Heel raise double leg",
   "Heel raise single leg",
   "Eccentric heel drop",
   "Inversion with band",
   "Eversion with band",
   "Towel scrunch",
   "Toe spread",
   "Short foot exercise",
   "Single leg balance",
   "Single leg balance on foam",
   "Wobble board",
   "Hop and hold",
   "Lateral hop"
  ],
  "Balance & return to sport": [
   "Single leg balance eyes open",
   "Single leg balance eyes closed",
   "Balance on bosu",
   "Land and hold single leg",
   "Land and hold with ball throw",
   "Vertical jump",
   "Vertical jump with split leg on bosu",
   "Box jump",
   "Drop jump",
   "Broad jump",
   "Lateral bound",
   "Agility ladder",
   "Change of direction drill",
   "Sprint progression",
   "Plyometric progression",
   "Sport-specific drill"
  ],
  "Pilates & general conditioning": [
   "Pilates reformer — footwork",
   "Pilates reformer — leg circles",
   "Pilates mat — hundred",
   "Pilates mat — roll up",
   "Pilates — spine stretch",
   "Pilates — swan",
   "Stationary bike",
   "Treadmill",
   "Cross trainer",
   "Rowing machine",
   "General mobility circuit"
  ]
 },
 "EX_DOSAGE": [
  "10 x 3 sets",
  "12 x 3 sets",
  "15 x 3 sets",
  "20 x 3 sets",
  "10 sec hold x 10",
  "30 sec hold x 3",
  "5 sec hold x 10",
  "daily",
  "twice daily",
  "3 times per week",
  "every other day"
 ],
 "DIAGNOSES": {
  "Neck & upper back": [
   "Muscle tightness",
   "Neck muscle tightness",
   "Myofascial pain syndrome (MPS)",
   "MPS at upper trapezius",
   "MPS with cranio-cervical tension",
   "MPS at sub-occipital",
   "Cervical facet joint hypomobility with muscle imbalance",
   "Upper cross syndrome",
   "Upper and lower cross syndrome",
   "Cervical radiculopathy",
   "Cervical spondylosis",
   "Cervical disc herniation",
   "Whiplash-associated disorder",
   "Tension-type headache",
   "Cervicogenic headache",
   "Postural neck pain",
   "Text neck",
   "Thoracic outlet syndrome",
   "Neck muscle strain",
   "Neck muscle spasm",
   "MPS with muscle tightness",
   "Scapular dyskinesis",
   "Levator scapulae strain",
   "Thoracic facet dysfunction",
   "Costovertebral joint dysfunction",
   "Acute torticollis"
  ],
  "Shoulder": [
   "Frozen shoulder (adhesive capsulitis)",
   "Left frozen shoulder",
   "Supraspinatus tendinopathy",
   "Supraspinatus tear",
   "Infraspinatus tendinopathy",
   "Subscapularis tendinopathy",
   "Biceps tendinopathy",
   "Long head of biceps tendinopathy",
   "Rotator cuff tear",
   "Rotator cuff tendinitis",
   "Subacromial impingement",
   "Shoulder impingement syndrome",
   "Subacromial bursitis",
   "Shoulder instability",
   "AC joint sprain",
   "SC joint sprain",
   "Labral tear",
   "Post-operative shoulder rehabilitation",
   "Calcific tendinitis"
  ],
  "Elbow, wrist & hand": [
   "Lateral epicondylitis (tennis elbow)",
   "Medial epicondylitis (golfer's elbow)",
   "Medial epicondyle tendinopathy",
   "De Quervain's tenosynovitis",
   "Carpal tunnel syndrome",
   "Cubital tunnel syndrome",
   "Trigger finger",
   "Wrist extensor group strain",
   "Thumb tightness / thenar overuse",
   "TFCC injury",
   "Wrist sprain",
   "Ganglion",
   "Dupuytren's contracture",
   "Post-fracture wrist rehabilitation"
  ],
  "Low back & pelvis": [
   "Lumbar muscle tightness",
   "Acute back muscle strain",
   "Chronic muscle strain",
   "Acute sacroiliac synovitis",
   "Sacroiliac joint dysfunction",
   "SIJ dysfunction with muscle strain",
   "Lumbar disc bulging",
   "Acute disc bulging",
   "Lumbar disc herniation",
   "HNP (herniated nucleus pulposus)",
   "Sciatic nerve irritation",
   "Sciatica",
   "Lumbar facet joint dysfunction",
   "Lumbar instability",
   "Spondylolisthesis",
   "Spondylolysis",
   "Lumbar spinal stenosis",
   "Postural low back pain",
   "Degenerative disc disease",
   "Pregnancy-related pelvic girdle pain",
   "Postpartum pelvic floor weakness",
   "Coccydynia",
   "Piriformis syndrome",
   "Gluteal muscle strain"
  ],
  "Hip & thigh": [
   "ITB tightness",
   "ITB syndrome",
   "Gluteal tendinopathy",
   "Hip impingement (FAI)",
   "Hip osteoarthritis",
   "Hip labral tear",
   "Hamstring strain",
   "Adductor strain",
   "Quadriceps strain",
   "Trochanteric bursitis",
   "Snapping hip syndrome",
   "Hip flexor tightness",
   "Post hip replacement rehabilitation",
   "Sports hernia / athletic groin pain",
   "Hip necrosis (AVN)"
  ],
  "Knee": [
   "Patellofemoral pain syndrome",
   "Right patellofemoral pain",
   "Patellar tendinosis",
   "Patellar tendinopathy",
   "ACL tear",
   "Post ACL reconstruction rehabilitation",
   "ACLR post-operative — allograft",
   "PCL injury",
   "Meniscus tear",
   "MCL sprain",
   "LCL sprain",
   "Knee osteoarthritis",
   "Osgood-Schlatter disease",
   "Quadriceps weakness / atrophy",
   "Iliotibial band friction syndrome",
   "Pes anserine bursitis",
   "Prepatellar bursitis",
   "Post total knee replacement rehabilitation",
   "Runner's knee"
  ],
  "Ankle & foot": [
   "Ankle sprain",
   "Lateral ligament ankle sprain",
   "Achilles tendinitis",
   "Achilles tendinopathy",
   "Plantar fasciitis",
   "Post-operative ankle rehabilitation",
   "Ankle instability",
   "Bone contusion",
   "Metatarsalgia",
   "Tibialis posterior dysfunction",
   "Shin splints",
   "Medial tibial stress syndrome",
   "Morton's neuroma",
   "Hallux valgus",
   "Peroneal tendinopathy",
   "Heel spur",
   "Post ankle fracture rehabilitation"
  ],
  "General, sport & other": [
   "General muscle tightness",
   "Muscle spasm",
   "Muscle tightness from hormonal changes during pregnancy",
   "Postural dysfunction",
   "Deconditioning",
   "Sports overuse injury",
   "Running-related injury",
   "Post-competition muscle fatigue",
   "Delayed onset muscle soreness",
   "Scoliosis",
   "Sedentary lifestyle-related pain",
   "Fibromyalgia",
   "Generalised hypermobility",
   "Work-related musculoskeletal disorder",
   "Office syndrome",
   "Muscle imbalance",
   "Poor posture",
   "Muscle strain",
   "Muscle tension",
   "Overuse",
   "Lower cross syndrome",
   "Restless legs syndrome"
  ]
 },
 "PLAN_GOALS": [
  "Reduce pain",
  "Pain control",
  "Inflammation control",
  "Reduce swelling",
  "Reduce tenderness",
  "Reduce muscle tension",
  "Release muscle tension",
  "Maintain ROM and muscle strength",
  "Maintain muscle and joint mobility",
  "Increase ROM",
  "Improve muscle power",
  "Improve muscle strength",
  "Improve posture",
  "Improve balance and proprioception",
  "Improve scapular control",
  "Improve core stability",
  "Correct movement pattern",
  "Return to sport",
  "Return to work",
  "Home programme progression",
  "Patient education",
  "Education and empowerment",
  "Prevent recurrence",
  "Decrease pain",
  "Relieve pain",
  "Improve joint mobility",
  "Improve mobility",
  "Improve range of motion",
  "Improve muscle flexibility",
  "Decrease pain and release muscle tension",
  "Reduce pain and muscle tension",
  "Continue as same plan",
  "Same plan"
 ],
 "IMPAIRMENTS": [
  "Pain",
  "Inflammation",
  "Limited ROM",
  "Muscle tightness",
  "Muscle weakness"
 ],
 "PARTICIPATION_RESTRICTION": [
  "No",
  "ADL & Family",
  "Study & work",
  "Exercise or Recreation",
  "Sport or Extreme exs."
 ],
 "PROGRESS": [
  "Poor",
  "Fair",
  "Good",
  "Excellent"
 ],
 "OUTPUT_FORMATS": {
  "SOAP with treatment": [
   "Subjective",
   "Objective",
   "Analysis",
   "Plan",
   "Treatment"
  ],
  "New patient's record": [
   "Chief complaint",
   "Diagnosis",
   "Pain scale",
   "Present history",
   "Past history",
   "Observation",
   "Palpation",
   "Active range of motions",
   "Passive range of motions",
   "Muscle power",
   "PAIVMS",
   "Functional test",
   "Special test",
   "Neurological examination",
   "Treatment",
   "Problem list"
  ],
  "Physiotherapy Report": [
   "Chief Complaint",
   "Physical Examinations",
   "Diagnosis",
   "Recommendation",
   "Physiotherapy Treatments"
  ]
 },
 "CORE_FIELDS": {
  "SOAP with treatment": [
   "Subjective",
   "Objective",
   "Analysis",
   "Plan",
   "Treatment"
  ],
  "New patient's record": [
   "Chief complaint",
   "Diagnosis",
   "Present history",
   "Observation",
   "Palpation",
   "Treatment"
  ],
  "Physiotherapy Report": [
   "Chief Complaint",
   "Physical Examinations",
   "Diagnosis",
   "Recommendation",
   "Physiotherapy Treatments"
  ]
 }
};
